# Dependabot is used to notify us about available dependency updates

# Config spec
version: 2

updates:
# Maven dependency updates
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      # Include dependencies in commit message
      include: "scope"

# Check for updates on GitHub workflows too
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Include dependencies in commit message
      include: "scope"
